spring:
  application:
    name: shopping-cart

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home_tech
    username: postgres
    password: postgres

  sql:
    init:
      mode: always
      schema-locations: classpath:/db/shopping-cart-schema.sql

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: shopping_cart
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,env

resilience4j:
  circuitbreaker:
    instances:
      warehouse:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true