server:
  port: ${COLLECTOR_HTTP_PORT:8080}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

collector:
  kafka:
    topics:
      sensors: ${KAFKA_TOPIC_SENSORS:telemetry.sensors.v1}
      hubs: ${KAFKA_TOPIC_HUBS:telemetry.hubs.v1}